<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'name' => 'รำละเอียด',
                'regular_price_per_kg' => 9.30,
                'regular_price_per_bag' => 279,
                'credit_price_per_kg' => 9.50,
                'credit_price_per_bag' => 285,
                'kg_per_bag_conversion' => 30.00,
            ],
            [
                'name' => 'รำสกัด',
                'regular_price_per_kg' => 7.50,
                'regular_price_per_bag' => 375,
                'credit_price_per_kg' => 7.70,
                'credit_price_per_bag' => 385,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'ปลายข้าว (เม็ด)',
                'regular_price_per_kg' => 11.30,
                'regular_price_per_bag' => 543,
                'credit_price_per_kg' => 11.50,
                'credit_price_per_bag' => 552,
                'kg_per_bag_conversion' => 48.00,
            ],
            [
                'name' => 'ปลายข้าวบด',
                'regular_price_per_kg' => 11.70,
                'regular_price_per_bag' => 585,
                'credit_price_per_kg' => 11.90,
                'credit_price_per_bag' => 595,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'ข้าวโพดบด',
                'regular_price_per_kg' => 12.00,
                'regular_price_per_bag' => 540,
                'credit_price_per_kg' => 12.20,
                'credit_price_per_bag' => 549,
                'kg_per_bag_conversion' => 45.00,
            ],
            [
                'name' => 'ข้าวโพดบดหยาบ',
                'regular_price_per_kg' => 12.00,
                'regular_price_per_bag' => 540,
                'credit_price_per_kg' => 12.20,
                'credit_price_per_bag' => 549,
                'kg_per_bag_conversion' => 45.00,
            ],
            [
                'name' => 'ข้าวโพดเม็ด',
                'regular_price_per_kg' => 11.60,
                'regular_price_per_bag' => 522,
                'credit_price_per_kg' => 11.80,
                'credit_price_per_bag' => 531,
                'kg_per_bag_conversion' => 45.00,
            ],
            [
                'name' => 'มันสำปะหลังบด',
                'regular_price_per_kg' => 8.60,
                'regular_price_per_bag' => 430,
                'credit_price_per_kg' => 8.80,
                'credit_price_per_bag' => 440,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'มันสำปะหลังสับเส้น',
                'regular_price_per_kg' => 8.60,
                'regular_price_per_bag' => 430,
                'credit_price_per_kg' => 8.80,
                'credit_price_per_bag' => 440,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'กากถั่วเหลือง 45%',
                'regular_price_per_kg' => 15.50,
                'regular_price_per_bag' => 775,
                'credit_price_per_kg' => 15.70,
                'credit_price_per_bag' => 785,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'ถั่วอบ 37%',
                'regular_price_per_kg' => 19.80,
                'regular_price_per_bag' => 990,
                'credit_price_per_kg' => 20.00,
                'credit_price_per_bag' => 1000,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'ปลาป่น 55%',
                'regular_price_per_kg' => 29.00,
                'regular_price_per_bag' => 1450,
                'credit_price_per_kg' => 29.20,
                'credit_price_per_bag' => 1460,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'ผิวถั่ว (โม่) 8-12',
                'regular_price_per_kg' => 7.60,
                'regular_price_per_bag' => 304,
                'credit_price_per_kg' => 7.80,
                'credit_price_per_bag' => 312,
                'kg_per_bag_conversion' => 40.00,
            ],
            [
                'name' => 'ผิวถั่ว (อัดเม็ด)',
                'regular_price_per_kg' => 7.60,
                'regular_price_per_bag' => 380,
                'credit_price_per_kg' => 7.80,
                'credit_price_per_bag' => 390,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'ผิวถั่ว (ท้องไข่)',
                'regular_price_per_kg' => 11.40,
                'regular_price_per_bag' => 170,
                'credit_price_per_kg' => 11.60,
                'credit_price_per_bag' => 174,
                'kg_per_bag_conversion' => 15.00,
            ],
            [
                'name' => 'กากเนื้อในปาล์ม',
                'regular_price_per_kg' => 5.60,
                'regular_price_per_bag' => 280,
                'credit_price_per_kg' => 5.80,
                'credit_price_per_bag' => 290,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'กากมัน 2%',
                'regular_price_per_kg' => 5.50,
                'regular_price_per_bag' => 247,
                'credit_price_per_kg' => 5.70,
                'credit_price_per_bag' => 256,
                'kg_per_bag_conversion' => 45.00,
            ],
            [
                'name' => 'กระถินป่น',
                'regular_price_per_kg' => 11.00,
                'regular_price_per_bag' => 550,
                'credit_price_per_kg' => 11.20,
                'credit_price_per_bag' => 560,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'พรีมิกซ์โค',
                'regular_price_per_kg' => 44.00,
                'regular_price_per_bag' => 1100,
                'credit_price_per_kg' => 44.40,
                'credit_price_per_bag' => 1110,
                'kg_per_bag_conversion' => 25.00,
            ],
            [
                'name' => 'พรีมิกซ์ไก่ไข่',
                'regular_price_per_kg' => 78.00,
                'regular_price_per_bag' => 1950,
                'credit_price_per_kg' => 78.40,
                'credit_price_per_bag' => 1960,
                'kg_per_bag_conversion' => 25.00,
            ],
            [
                'name' => 'อาหารโคเนื้อ 14%',
                'regular_price_per_kg' => 9.70,
                'regular_price_per_bag' => 290,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 30.00,
            ],
            [
                'name' => 'อาหารโคเนื้อ',
                'regular_price_per_kg' => null,
                'regular_price_per_bag' => 282,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 30.00,
            ],
            [
                'name' => 'กากปาล์มรวม',
                'regular_price_per_kg' => 4.70,
                'regular_price_per_bag' => 235,
                'credit_price_per_kg' => 4.90,
                'credit_price_per_bag' => 245,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'เปลือกหอย',
                'regular_price_per_kg' => 4.00,
                'regular_price_per_bag' => 270,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 70.00,
            ],
            [
                'name' => 'เกลือ',
                'regular_price_per_kg' => 5.70,
                'regular_price_per_bag' => 170,
                'credit_price_per_kg' => 5.90,
                'credit_price_per_bag' => 175,
                'kg_per_bag_conversion' => 30.00,
            ],
            [
                'name' => 'P 18',
                'regular_price_per_kg' => 7.60,
                'regular_price_per_bag' => 380,
                'credit_price_per_kg' => 7.80,
                'credit_price_per_bag' => 390,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'P 21',
                'regular_price_per_kg' => 35.00,
                'regular_price_per_bag' => null,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'กากน้ำตาล',
                'regular_price_per_kg' => 10.00,
                'regular_price_per_bag' => null,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => null,
            ],
            [
                'name' => 'สารสีแดง',
                'regular_price_per_kg' => 250.00,
                'regular_price_per_bag' => 250,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'DL-เมไธโอนีน',
                'regular_price_per_kg' => 125.00,
                'regular_price_per_bag' => 125,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'L-ไลซีน',
                'regular_price_per_kg' => 80.00,
                'regular_price_per_bag' => 80,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'L-ทรีโอนีน',
                'regular_price_per_kg' => 90.00,
                'regular_price_per_bag' => 90,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'หินฝุ่น',
                'regular_price_per_kg' => 3.00,
                'regular_price_per_bag' => 150,
                'credit_price_per_kg' => 3.20,
                'credit_price_per_bag' => 160,
                'kg_per_bag_conversion' => 50.00,
            ],
            [
                'name' => 'รอสโพรไซม์',
                'regular_price_per_kg' => 300.00,
                'regular_price_per_bag' => 300,
                'credit_price_per_kg' => 310.00,
                'credit_price_per_bag' => 310,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'จับรา',
                'regular_price_per_kg' => 160.00,
                'regular_price_per_bag' => 160,
                'credit_price_per_kg' => 170.00,
                'credit_price_per_bag' => 170,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'ซันเฟส',
                'regular_price_per_kg' => 300.00,
                'regular_price_per_bag' => 300,
                'credit_price_per_kg' => 310.00,
                'credit_price_per_bag' => 310,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'รูเมนยีสต์',
                'regular_price_per_kg' => 300.00,
                'regular_price_per_bag' => 300,
                'credit_price_per_kg' => 310.00,
                'credit_price_per_bag' => 310,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'วิตามินบี',
                'regular_price_per_kg' => 220.00,
                'regular_price_per_bag' => 220,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'กำมะถัน',
                'regular_price_per_kg' => 52.00,
                'regular_price_per_bag' => 1300,
                'credit_price_per_kg' => 52.20,
                'credit_price_per_bag' => 1305,
                'kg_per_bag_conversion' => 25.00,
            ],
            [
                'name' => 'พรีมิกซ์หมูเล็ก-รุ่น',
                'regular_price_per_kg' => 180.00,
                'regular_price_per_bag' => null,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'พรีมิกซ์หมูรุ่น-ขุน',
                'regular_price_per_kg' => 135.00,
                'regular_price_per_bag' => null,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 1.00,
            ],
            [
                'name' => 'พรีมิกซ์หมูแม่พันธุ์',
                'regular_price_per_kg' => 125.00,
                'regular_price_per_bag' => null,
                'credit_price_per_kg' => null,
                'credit_price_per_bag' => null,
                'kg_per_bag_conversion' => 1.00,
            ],
        ];

        foreach ($items as $itemData) {
            Item::create($itemData);
        }
    }
}